export const mockUsers = [
  {
    id: 1,
    name: 'Dr. John Smith',
    email: 'john.smith@hospital.com',
    role: 'doctor',
    department: 'Cardiology',
    status: 'Active',
  },
  {
    id: 2,
    name: 'Nurse Sarah Johnson',
    email: 'sarah.johnson@hospital.com',
    role: 'nurse',
    department: 'Emergency',
    status: 'Active',
  },
  {
    id: 3,
    name: 'Michael Brown',
    email: 'michael.brown@hospital.com',
    role: 'staff',
    department: 'Administration',
    status: 'Active',
  },
  {
    id: 4,
    name: 'Dr. Emily Davis',
    email: 'emily.davis@hospital.com',
    role: 'doctor',
    department: 'Pediatrics',
    status: 'Inactive',
  },
  {
    id: 5,
    name: 'Patient Jane Doe',
    email: 'jane.doe@email.com',
    role: 'patient',
    department: 'N/A',
    status: 'Active',
  },
  {
    id: 6,
    name: 'Dr. Robert Wilson',
    email: 'robert.wilson@hospital.com',
    role: 'doctor',
    department: 'Neurology',
    status: 'Active',
  },
  {
    id: 7,
    name: 'Nurse Maria Rodriguez',
    email: 'maria.rodriguez@hospital.com',
    role: 'nurse',
    department: 'ICU',
    status: 'Active',
  },
  {
    id: 8,
    name: 'Dr. Lisa Chen',
    email: 'lisa.chen@hospital.com',
    role: 'doctor',
    department: 'Oncology',
    status: 'Active',
  },
  {
    id: 9,
    name: 'Nurse James Thompson',
    email: 'james.thompson@hospital.com',
    role: 'nurse',
    department: 'Surgery',
    status: 'Active',
  },
  {
    id: 10,
    name: 'David Martinez',
    email: 'david.martinez@hospital.com',
    role: 'staff',
    department: 'IT Support',
    status: 'Active',
  },
  {
    id: 11,
    name: 'Dr. Amanda White',
    email: 'amanda.white@hospital.com',
    role: 'doctor',
    department: 'Radiology',
    status: 'Active',
  },
  {
    id: 12,
    name: 'Nurse Kevin Park',
    email: 'kevin.park@hospital.com',
    role: 'nurse',
    department: 'Maternity',
    status: 'Inactive',
  },
  {
    id: 13,
    name: 'Patient Robert Johnson',
    email: 'robert.johnson@email.com',
    role: 'patient',
    department: 'N/A',
    status: 'Active',
  },
  {
    id: 14,
    name: 'Dr. Steven Lee',
    email: 'steven.lee@hospital.com',
    role: 'doctor',
    department: 'Orthopedics',
    status: 'Active',
  },
  {
    id: 15,
    name: 'Jennifer Adams',
    email: 'jennifer.adams@hospital.com',
    role: 'staff',
    department: 'HR',
    status: 'Active',
  },
  {
    id: 16,
    name: 'Nurse Patricia Garcia',
    email: 'patricia.garcia@hospital.com',
    role: 'nurse',
    department: 'Pediatrics',
    status: 'Active',
  },
  {
    id: 17,
    name: 'Dr. Christopher Taylor',
    email: 'christopher.taylor@hospital.com',
    role: 'doctor',
    department: 'Gastroenterology',
    status: 'Active',
  },
  {
    id: 18,
    name: 'Patient Mary Williams',
    email: 'mary.williams@email.com',
    role: 'patient',
    department: 'N/A',
    status: 'Active',
  },
  {
    id: 19,
    name: 'Nurse Daniel Moore',
    email: 'daniel.moore@hospital.com',
    role: 'nurse',
    department: 'Emergency',
    status: 'Active',
  },
  {
    id: 20,
    name: 'Angela Wright',
    email: 'angela.wright@hospital.com',
    role: 'staff',
    department: 'Finance',
    status: 'Active',
  },
  {
    id: 21,
    name: 'Dr. Michelle Turner',
    email: 'michelle.turner@hospital.com',
    role: 'doctor',
    department: 'Dermatology',
    status: 'Inactive',
  },
  {
    id: 22,
    name: 'Nurse Thomas Anderson',
    email: 'thomas.anderson@hospital.com',
    role: 'nurse',
    department: 'Cardiology',
    status: 'Active',
  },
  {
    id: 23,
    name: 'Patient Sandra Brown',
    email: 'sandra.brown@email.com',
    role: 'patient',
    department: 'N/A',
    status: 'Active',
  },
  {
    id: 24,
    name: 'Dr. Brian Clark',
    email: 'brian.clark@hospital.com',
    role: 'doctor',
    department: 'Psychiatry',
    status: 'Active',
  },
  {
    id: 25,
    name: 'Rebecca Hill',
    email: 'rebecca.hill@hospital.com',
    role: 'staff',
    department: 'Pharmacy',
    status: 'Active',
  },
];

export const initialFormData = {
  name: '',
  email: '',
  role: '',
  department: '',
  status: 'Active',
};
