import {
  AdminPanelSettings as AdminIcon,
  LocalHospital as DoctorIcon,
  MedicalServices as NurseIcon,
  Business as StaffIcon,
  PersonOutline as PatientIcon,
} from '@mui/icons-material';

export const permissionLabels = {
  // Admin permissions
  canManageUsers: 'Manage Users',
  canViewSystemReports: 'View System Reports',
  canManageHospitalSettings: 'Manage Hospital Settings',

  // Doctor permissions
  canViewPatientRecords: 'View Patient Records',
  canScheduleAppointments: 'Schedule Appointments',
  canWritePrescriptions: 'Write Prescriptions',

  // Nurse permissions
  canManagePatientCare: 'Patient Care Tasks',
  canManageMedications: 'Medication Schedule',
  canRecordVitalSigns: 'Vital Signs Entry',

  // Staff permissions
  canManageAppointments: 'Appointment Management',
  canRegisterPatients: 'Patient Registration',
  canProcessInsurance: 'Insurance Processing',

  // Patient permissions
  canBookAppointments: 'Book Appointments',
  canViewTestResults: 'View Test Results',
  canPayBills: 'Pay Bills',
};

export const roleConfig = {
  admin: { color: 'error', icon: <AdminIcon /> },
  staff: { color: 'info', icon: <StaffIcon /> },
  doctor: { color: 'success', icon: <DoctorIcon /> },
  nurse: { color: 'primary', icon: <NurseIcon /> },
  patient: { color: 'secondary', icon: <PatientIcon /> },
};

export const allRolePermissions = {
  admin: {
    canManageUsers: true,
    canViewSystemReports: true,
    canManageHospitalSettings: true,
    canViewPatientRecords: false,
    canScheduleAppointments: false,
    canWritePrescriptions: false,
    canManagePatientCare: false,
    canManageMedications: false,
    canRecordVitalSigns: false,
    canManageAppointments: false,
    canRegisterPatients: false,
    canProcessInsurance: false,
    canBookAppointments: false,
    canViewTestResults: false,
    canPayBills: false,
  },
  doctor: {
    canManageUsers: false,
    canViewSystemReports: false,
    canManageHospitalSettings: false,
    canViewPatientRecords: true,
    canScheduleAppointments: true,
    canWritePrescriptions: true,
    canManagePatientCare: false,
    canManageMedications: false,
    canRecordVitalSigns: false,
    canManageAppointments: false,
    canRegisterPatients: false,
    canProcessInsurance: false,
    canBookAppointments: false,
    canViewTestResults: false,
    canPayBills: false,
  },
  nurse: {
    canManageUsers: false,
    canViewSystemReports: false,
    canManageHospitalSettings: false,
    canViewPatientRecords: false,
    canScheduleAppointments: false,
    canWritePrescriptions: false,
    canManagePatientCare: true,
    canManageMedications: true,
    canRecordVitalSigns: true,
    canManageAppointments: false,
    canRegisterPatients: false,
    canProcessInsurance: false,
    canBookAppointments: false,
    canViewTestResults: false,
    canPayBills: false,
  },
  staff: {
    canManageUsers: false,
    canViewSystemReports: false,
    canManageHospitalSettings: false,
    canViewPatientRecords: false,
    canScheduleAppointments: false,
    canWritePrescriptions: false,
    canManagePatientCare: false,
    canManageMedications: false,
    canRecordVitalSigns: false,
    canManageAppointments: true,
    canRegisterPatients: true,
    canProcessInsurance: true,
    canBookAppointments: false,
    canViewTestResults: false,
    canPayBills: false,
  },
  patient: {
    canManageUsers: false,
    canViewSystemReports: false,
    canManageHospitalSettings: false,
    canViewPatientRecords: false,
    canScheduleAppointments: false,
    canWritePrescriptions: false,
    canManagePatientCare: false,
    canManageMedications: false,
    canRecordVitalSigns: false,
    canManageAppointments: false,
    canRegisterPatients: false,
    canProcessInsurance: false,
    canBookAppointments: true,
    canViewTestResults: true,
    canPayBills: true,
  },
};
